# Generated by Django 5.0.7 on 2024-07-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mname', models.CharField(max_length=255)),
                ('Mrole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tipo', to='events.roles')),
            ],
            options={
                'verbose_name': 'Material',
            },
        ),
        migrations.CreateModel(
            name='Techcrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(max_length=255)),
                ('Trole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papel', to='events.roles')),
            ],
            options={
                'verbose_name': 'techcrew',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('Evname', models.CharField(max_length=255)),
                ('Evdate', models.DateField()),
                ('Evlocation', models.CharField(max_length=255)),
                ('Evmaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='events.material')),
                ('Evleader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techs', to='events.techcrew')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
