# Generated by Django 5.0.7 on 2024-07-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_evid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Evid',
        ),
    ]
