# Generated by Django 5.0.7 on 2024-07-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_course_remove_material_mrole_remove_techcrew_trole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
