# Generated by Django 5.0.7 on 2025-07-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_course_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prepareTime', models.CharField(max_length=50)),
                ('dificulty', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=50)),
                ('prepareSteps', models.CharField(max_length=50)),
                ('isVegan', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
    ]
